# Generated by Django 5.0.13 on 2025-04-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserver',
            name='tool_name',
            field=models.CharField(blank=True, help_text='Name of the tool provided by this MCP server', max_length=255, verbose_name='Tool Name'),
        ),
    ]
