# Generated by Django 5.0.13 on 2025-05-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcpserver',
            name='url',
            field=models.URLField(max_length=255, verbose_name='URL'),
        ),
    ]
