# Generated by Django 5.0.13 on 2025-04-11 19:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('system_prompt', models.TextField(verbose_name='System Prompt')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'db_table': 'agents_agent',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LLM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('api_type', models.CharField(choices=[('ollama', 'Ollama'), ('gemini', 'Gemini')], max_length=10, verbose_name='API Type')),
                ('model', models.CharField(help_text='The specific model name for the selected API type', max_length=100, verbose_name='Model')),
                ('api_key', models.CharField(blank=True, help_text='API key for authentication (stored securely in Vault)', max_length=255, verbose_name='API Key')),
                ('max_tokens', models.PositiveIntegerField(default=4096, help_text='Maximum number of tokens for generation', verbose_name='Max Tokens')),
            ],
            options={
                'verbose_name': 'LLM',
                'verbose_name_plural': 'LLMs',
                'db_table': 'agents_llm',
                'ordering': ['api_type', 'model'],
            },
        ),
    ]
