# Generated by Django 5.0.13 on 2025-05-08 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
        ('llms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='llm',
            field=models.ForeignKey(blank=True, help_text='The LLM model this agent uses for responses', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='llms.llm', verbose_name='LLM Model'),
        ),
    ]
