# Generated by Django 5.0.13 on 2025-04-25 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0002_initial'),
        ('organization', '0001_initial'),
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='mcp_servers',
            field=models.ManyToManyField(blank=True, help_text='The MCP servers this agent is connected to', related_name='agents', to='tools.mcpserver', verbose_name='MCP Servers'),
        ),
        migrations.AddField(
            model_name='agent',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='organization.organization', verbose_name='Organization'),
        ),
    ]
