# Generated by Django 5.0.13 on 2025-05-06 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='is_public',
        ),
    ]
