# Generated by Django 5.0.13 on 2025-04-16 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this agent is publicly visible to other users in the organization', verbose_name='Public'),
        ),
    ]
