# Generated by Django 5.0.13 on 2025-04-24 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_agent_is_public'),
        ('tools', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='mcp_servers',
            field=models.ManyToManyField(blank=True, help_text='The MCP servers this agent is connected to', related_name='agents', to='tools.mcpserver', verbose_name='MCP Servers'),
        ),
    ]
