# Use Node.js 22.15 as the base image
FROM node:22.15-alpine AS base


# Install pnpm
RUN npm install -g pnpm


# Create app directory
WORKDIR /app


# Copy package.json and pnpm-lock.yaml
COPY ./frontend/package.json ./frontend/pnpm-lock.yaml* ./


# Install dependencies
RUN pnpm install


# Copy the rest of the application
COPY ./frontend ./


# Build the application
RUN pnpm build


# Copy scripts and set permissions - combine operations to reduce layers
COPY ./compose/nextjs/entrypoint /entrypoint
COPY ./compose/nextjs/start /start


# Set permissions
RUN sed -i 's/\r$//g' /entrypoint /start && chmod +x /entrypoint /start


# Set permissions
RUN sed -i 's/\r$//g' /entrypoint /start


# Set environment variables
ENV NODE_ENV=production


# Set the user to node
USER node


# Set the entrypoint
ENTRYPOINT ["/entrypoint"]
