# Use Node.js 22.15 as the base image
FROM node:22.15-alpine AS base


# Install pnpm
RUN npm install -g pnpm


# Create app directory
WORKDIR /app


# Copy package.json and pnpm-lock.yaml
COPY ./frontend/package.json ./frontend/pnpm-lock.yaml* ./


# Install dependencies
RUN pnpm install


# Copy the rest of the application
COPY ./frontend ./


# Build the application (Defaults to production mode)
RUN pnpm build


# Copy scripts and set permissions
COPY ./compose/nextjs/entrypoint /entrypoint
COPY ./compose/nextjs/start /start
RUN sed -i 's/\r$//g' /entrypoint /start && chmod +x /entrypoint /start


# Change ownership before switching user
RUN chown -R node:node /app


# Set the user to node
USER node


# Set the entrypoint
ENTRYPOINT ["/entrypoint"]
