# Generated by Django 5.0.13 on 2025-04-05 12:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeletionToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('uid', models.CharField(max_length=255, verbose_name='User ID')),
                ('token', models.CharField(max_length=255, verbose_name='Deletion Token')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_tokens', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Deletion Token',
                'verbose_name_plural': 'User Deletion Tokens',
                'db_table': 'users_user_deletion_token',
                'ordering': ['-created_at'],
                'unique_together': {('uid', 'token')},
            },
        ),
    ]
