# Generated by Django 5.0.13 on 2025-04-25 20:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('content', models.TextField(verbose_name='Content')),
                ('sender', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], max_length=10, verbose_name='Sender')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'chats_message',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='SingleChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this chat is publicly visible to other users in the organization', verbose_name='Public')),
                ('summary', models.TextField(blank=True, default='', help_text='A summary of the chat conversation', verbose_name='Summary')),
            ],
            options={
                'verbose_name': 'Single Chat',
                'verbose_name_plural': 'Single Chats',
                'db_table': 'chats_single_chat',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('is_public', models.BooleanField(default=False, help_text='Whether this chat is publicly visible to other users in the organization', verbose_name='Public')),
                ('summary', models.TextField(blank=True, default='', help_text='A summary of the chat conversation', verbose_name='Summary')),
                ('agents', models.ManyToManyField(help_text='The agents participating in this group chat', related_name='group_chats', to='agents.agent', verbose_name='Agents')),
            ],
            options={
                'verbose_name': 'Group Chat',
                'verbose_name_plural': 'Group Chats',
                'db_table': 'chats_group_chat',
                'ordering': ['-created_at'],
            },
        ),
    ]
