# Generated by Django 5.0.13 on 2025-04-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this chat is publicly visible to other users in the organization', verbose_name='Public'),
        ),
        migrations.AddField(
            model_name='singlechat',
            name='is_public',
            field=models.BooleanField(default=False, help_text='Whether this chat is publicly visible to other users in the organization', verbose_name='Public'),
        ),
    ]
