# Generated by Django 5.0.13 on 2025-04-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_groupchat_is_public_singlechat_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupchat',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='A summary of the chat conversation', verbose_name='Summary'),
        ),
        migrations.AddField(
            model_name='singlechat',
            name='summary',
            field=models.TextField(blank=True, default='', help_text='A summary of the chat conversation', verbose_name='Summary'),
        ),
    ]
