# Generated by Django 5.0.13 on 2025-04-24 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0003_groupchat_summary_singlechat_summary'),
        ('conversation', '0003_alter_session_selector_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversation.session', verbose_name='Session'),
        ),
    ]
