# Generated by Django 5.0.13 on 2025-05-08 10:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LLM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('base_url', models.URLField(default='https://api.openai.com/v1', help_text='The base URL for the LLM API', max_length=255, verbose_name='Base URL')),
                ('model', models.CharField(help_text='The specific model name to use with this LLM API', max_length=100, verbose_name='Model')),
                ('api_key', models.CharField(blank=True, help_text='API key for authentication (stored securely in Vault)', max_length=255, verbose_name='API Key')),
                ('max_tokens', models.PositiveIntegerField(default=4096, help_text='Maximum number of tokens for generation', verbose_name='Max Tokens')),
            ],
            options={
                'verbose_name': 'LLM',
                'verbose_name_plural': 'LLMs',
                'db_table': 'llms_llm',
                'ordering': ['model'],
            },
        ),
    ]
