# Generated by Django 5.0.13 on 2025-05-06 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llms', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='llm',
            options={'ordering': ['model'], 'verbose_name': 'LLM', 'verbose_name_plural': 'LLMs'},
        ),
        migrations.RemoveField(
            model_name='llm',
            name='api_type',
        ),
        migrations.AddField(
            model_name='llm',
            name='base_url',
            field=models.URLField(default='https://api.openai.com/v1', help_text='The base URL for the LLM API', max_length=255, verbose_name='Base URL'),
        ),
        migrations.AlterField(
            model_name='llm',
            name='model',
            field=models.CharField(help_text='The specific model name to use with this LLM API', max_length=100, verbose_name='Model'),
        ),
    ]
