# Generated by Django 5.0.13 on 2025-04-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('llms', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llm',
            name='api_type',
            field=models.CharField(choices=[('google', 'Google')], max_length=10, verbose_name='API Type'),
        ),
    ]
