# Generated by Django 5.0.13 on 2025-04-07 07:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0003_initial'),
        ('organization', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LLM',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('api_type', models.CharField(choices=[('ollama', 'Ollama'), ('gemini', 'Gemini')], max_length=10, verbose_name='API Type')),
                ('model', models.CharField(help_text='The specific model name for the selected API type', max_length=100, verbose_name='Model')),
                ('api_key', models.CharField(blank=True, help_text='API key for authentication (required for Gemini)', max_length=255, verbose_name='API Key')),
                ('max_tokens', models.PositiveIntegerField(default=4096, help_text='Maximum number of tokens for generation', verbose_name='Max Tokens')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='llm_configs', to='organization.organization', verbose_name='Organization')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_llm_configs', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
            ],
            options={
                'verbose_name': 'LLM',
                'verbose_name_plural': 'LLMs',
                'db_table': 'agents_llm',
                'ordering': ['api_type', 'model'],
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='llm',
            field=models.ForeignKey(blank=True, help_text='The LLM model this agent uses for responses', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='agents.llm', verbose_name='LLM Model'),
        ),
    ]
