# Generated by Django 5.0.13 on 2025-04-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0004_llm_agent_llm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llm',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for authentication provided by the API provider.', max_length=255, verbose_name='API Key'),
        ),
    ]
