# Generated by Django 5.0.13 on 2025-04-07 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0005_alter_llm_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='llm',
            name='api_key',
            field=models.CharField(blank=True, help_text='API key for authentication (stored securely in Vault)', max_length=255, verbose_name='API Key'),
        ),
    ]
