# Generated by Django 5.0.13 on 2025-04-25 20:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('name', models.CharField(max_length=100, verbose_name='Organization Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='organization_logos/', verbose_name='Logo')),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'db_table': 'organization_organization',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationOwnershipTransfer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('expiration_time', models.DateTimeField(verbose_name='Expiration Time')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Accepted Status')),
                ('is_rejected', models.BooleanField(default=False, verbose_name='Rejected Status')),
                ('is_expired', models.BooleanField(default=False, verbose_name='Expired Status')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Cancelled Status')),
            ],
            options={
                'verbose_name': 'Organization Ownership Transfer',
                'verbose_name_plural': 'Organization Ownership Transfers',
                'db_table': 'organization_ownership_transfer',
                'ordering': ['-created_at'],
            },
        ),
    ]
