# Generated by Django 5.0.13 on 2025-05-08 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='organizations', to=settings.AUTH_USER_MODEL, verbose_name='Members'),
        ),
        migrations.AddField(
            model_name='organization',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_organizations', to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AddField(
            model_name='organizationownershiptransfer',
            name='current_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiated_ownership_transfers', to=settings.AUTH_USER_MODEL, verbose_name='Current Owner'),
        ),
        migrations.AddField(
            model_name='organizationownershiptransfer',
            name='new_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_ownership_transfers', to=settings.AUTH_USER_MODEL, verbose_name='New Owner'),
        ),
        migrations.AddField(
            model_name='organizationownershiptransfer',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownership_transfers', to='organization.organization', verbose_name='Organization'),
        ),
        migrations.AlterUniqueTogether(
            name='organization',
            unique_together={('owner', 'name')},
        ),
    ]
