# Generated by Django 5.0.13 on 2025-04-15 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='is_active',
        ),
    ]
