# Generated by Django 5.0.13 on 2025-04-25 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chats', '0001_initial'),
        ('conversation', '0001_initial'),
        ('llms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='llm',
            field=models.ForeignKey(blank=True, help_text='The LLM model used for this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='llms.llm', verbose_name='LLM Model'),
        ),
        migrations.AddField(
            model_name='session',
            name='single_chat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='chats.singlechat', verbose_name='Single Chat'),
        ),
    ]
