# Generated by Django 5.0.13 on 2025-04-20 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0001_initial'),
        ('llms', '0004_alter_llm_api_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='llm',
            field=models.ForeignKey(blank=True, help_text='The LLM model used for this session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='llms.llm', verbose_name='LLM Model'),
        ),
        migrations.AddField(
            model_name='session',
            name='selector_prompt',
            field=models.CharField(blank=True, default='', help_text='Prompt used for selecting the appropriate agent or tool', max_length=1000, verbose_name='Selector Prompt'),
        ),
    ]
