# Generated by Django 5.0.13 on 2025-04-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversation', '0002_session_llm_session_selector_prompt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='selector_prompt',
            field=models.TextField(blank=True, default='', help_text='Prompt used for selecting the appropriate agent or tool', verbose_name='Selector Prompt'),
        ),
    ]
